captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0
    open-captcha-timeout: 3600
cors:
    mode: strict-whitelist
    whitelist:
        -   allow-origin: example1.com
            allow-methods: POST, GET
            allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
            expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
            allow-credentials: true
        -   allow-origin: example2.com
            allow-methods: GET, POST
            allow-headers: content-type
            expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
            allow-credentials: true
db-list:
    -   type: ""
        alias-name: ""
        prefix: ""
        port: ""
        config: ""
        db-name: ""
        username: ""
        password: ""
        path: ""
        engine: ""
        log-mode: ""
        max-idle-conns: 10
        max-open-conns: 100
        singular: false
        log-zap: false
        disable: true
jwt:
    signing-key: 565caf6f-51f7-4c99-877a-f001b7ce95cd
    expires-time: 7d
    buffer-time: 1d
    issuer: report_outsource_api
minio:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    use-ssl: false
    base-path: ""
    bucket-url: http://host:9000/yourBucketName
mongo:
    coll: ""
    options: ""
    database: ""
    username: ""
    password: ""
    auth-source: ""
    min-pool-size: 0
    max-pool-size: 100
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts:
        -   host: ""
            port: ""
mssql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: report_outsource
    username: report_outsource_api
    password: Snwr6CmbSJr9fJYb4XCRzHX3ir
    path: taohaohao.rwlb.rds.aliyuncs.com
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 50
    singular: false
    log-zap: false
oracle:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
pgsql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
redis:
    name: ""
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    useCluster: false
    clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
sqlite:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
system:
    db-type: mysql
    router-prefix: ""
    addr: 10668
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: false
zap:
    level: info
    prefix: ""
    format: json
    director: log
    encode-level: LowercaseLevelEncoder
    stacktrace-key: stacktrace
    show-line: true
    log-in-console: true
    retention-day: -1
