definitions:
  request.LoginRequest:
    properties:
      code:
        type: string
      email:
        type: string
      login_type:
        description: 1 手机号登录 2邮箱登录 3密码登录
        enum:
        - 1
        - 2
        - 3
        type: integer
      password:
        maxLength: 20
        minLength: 8
        type: string
      phone:
        type: string
    required:
    - login_type
    - password
    type: object
  response.LoginResponse:
    properties:
      token:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
  description: 清欢-开箱即用简易后端框架
  title: qh-gin-api Swagger API接口文档
  version: v1.0.0
paths:
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 手机号 邮箱 密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录结果
          schema:
            $ref: '#/definitions/response.LoginResponse'
      security:
      - ApiKeyAuth: []
      summary: 用户登录
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID, 用户名, 昵称, 头像链接
        in: body
        name: data
        required: true
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
      security:
      - ApiKeyAuth: []
      summary: 用户注册
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
